"""empty message

Revision ID: 0aa4f99c20a4
Revises: 
Create Date: 2018-06-05 10:54:15.435649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa4f99c20a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('source', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribe', 'source')
    # ### end Alembic commands ###
