"""empty message

Revision ID: 2e67a541439f
Revises: 
Create Date: 2018-05-23 16:52:43.265092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e67a541439f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('subscribe', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('subscribe_ibfk_1', 'subscribe', type_='foreignkey')
    op.drop_constraint('subscribe_ibfk_2', 'subscribe', type_='foreignkey')
    op.create_foreign_key(None, 'subscribe', 'book', ['book_id'], ['id'])
    op.create_foreign_key(None, 'subscribe', 'user', ['user_id'], ['id'])
    op.drop_column('subscribe', 'book.id')
    op.drop_column('subscribe', 'user.id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('user.id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('subscribe', sa.Column('book.id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscribe', type_='foreignkey')
    op.drop_constraint(None, 'subscribe', type_='foreignkey')
    op.create_foreign_key('subscribe_ibfk_2', 'subscribe', 'book', ['book.id'], ['id'])
    op.create_foreign_key('subscribe_ibfk_1', 'subscribe', 'user', ['user.id'], ['id'])
    op.drop_column('subscribe', 'user_id')
    op.drop_column('subscribe', 'book_id')
    # ### end Alembic commands ###
